# Generated by Django 5.1.4 on 2025-01-16 04:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meeting Message',
                'verbose_name_plural': 'Meeting Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMessageAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, max_length=255)),
                ('suggestions', models.TextField(blank=True, max_length=255)),
                ('criticism', models.TextField(blank=True, max_length=255)),
                ('warning', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Meeting Message Annotation',
                'verbose_name_plural': 'Meeting Message Annotations',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('is_archived', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
            },
        ),
        migrations.CreateModel(
            name='MeetingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('is_kicked', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingmember', to='meeting.meeting')),
            ],
            options={
                'verbose_name': 'Meeting Member',
                'verbose_name_plural': 'Meeting Members',
            },
        ),
    ]
