# Generated by Django 5.1.5 on 2025-01-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meetingmember',
            name='unique_meeting_nickname',
        ),
        migrations.RemoveField(
            model_name='meetingmember',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='meetingmember',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='meetingmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingmember',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupmember'),
        ),
    ]
