# Generated by Django 5.1.4 on 2025-01-16 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingmember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingmessage',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='meetingmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meetingmember'),
        ),
        migrations.AddField(
            model_name='meetingmessageannotation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meetingmessage'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('group', 'title'), name='unique_group_title'),
        ),
        migrations.AddConstraint(
            model_name='meetingmember',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='unique_meeting_user'),
        ),
        migrations.AddConstraint(
            model_name='meetingmember',
            constraint=models.UniqueConstraint(fields=('meeting', 'nickname'), name='unique_meeting_member_nickname'),
        ),
    ]
