# Generated by Django 5.1.5 on 2025-01-17 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingmember',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='meetingmember',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingmember', to='meeting.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingmember', to=settings.AUTH_USER_MODEL),
        ),
    ]
