# Generated by Django 5.1.5 on 2025-01-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
