<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-01-18 10:29
=======
# Generated by Django 5.1.5 on 2025-01-18 11:01
>>>>>>> 1d0cc0215ab84251e36aec0526e4dfd04e6ff5e2

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_rename_is_banned_groupmember_is_kicked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'nickname'], name='group_group_group_i_cfe62f_idx'),
        ),
    ]
