# Generated by Django 5.1.4 on 2025-01-15 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('is_archived', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
            },
        ),
        migrations.CreateModel(
            name='DiscussionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('is_kicked', models.BooleanField(default=False)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussionmember', to='discussion.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussionmember', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion Member',
                'verbose_name_plural': 'Discussion Members',
            },
        ),
        migrations.CreateModel(
            name='DiscussionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.discussion')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.discussionmember')),
            ],
            options={
                'verbose_name': 'Discussion Message',
                'verbose_name_plural': 'Discussion Messages',
            },
        ),
        migrations.CreateModel(
            name='DiscussionMessageAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, max_length=255)),
                ('suggestions', models.TextField(blank=True, max_length=255)),
                ('criticism', models.TextField(blank=True, max_length=255)),
                ('warning', models.TextField(blank=True, max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.discussionmessage')),
            ],
            options={
                'verbose_name': 'Discussion Message Summary',
                'verbose_name_plural': 'Discussion Message Summaries',
            },
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['group', 'title'], name='discussion__group_i_f79a58_idx'),
        ),
        migrations.AddConstraint(
            model_name='discussionmember',
            constraint=models.UniqueConstraint(fields=('discussion', 'user'), name='unique_discussion_user'),
        ),
        migrations.AddConstraint(
            model_name='discussionmember',
            constraint=models.UniqueConstraint(fields=('discussion', 'nickname'), name='unique_discussion_member_nickname'),
        ),
    ]
